In [5]:
import numpy as np

# a = np.mat('4 6 8; 6 9 12;5 6 8')
# b = np.array([2.74,4.14,2.89])
# k=[]
# for i in [0,1,2]:
#     jieguo = np.delete(a,i,axis=1)
#     jieguo1 = np.insert(jieguo,i,b,axis=1)
#     jie = np.linalg.det(jieguo1)/np.linalg.det(a)
#     k.append(jie)
# k

A = np.mat('4 6 8;6 9 12;5 6 8')
C = np.array([2.74,4.14,2.89])
NA = np.linalg.inv(A)   # 线性库  linalg
np.matmul(NA,C)

LinAlgError: Singular matrix

In [4]:
a = np.mat('2 -1 -1 1;1 1 -2 1;4 -6 2 -2;3 6 -9 7')
a

matrix([[ 2, -1, -1,  1],
        [ 1,  1, -2,  1],
        [ 4, -6,  2, -2],
        [ 3,  6, -9,  7]])

In [9]:
np.linalg.matrix_rank(a)  # 矩阵的秩

3

# 向量的范数

In [2]:
import numpy as np
x = np.array([1, 0, -2])
n0 = np.linalg.norm(x, ord=0)# 0-范数，表示向量中非零元素的个数
n1 = np.linalg.norm(x, ord=1)#1-范数， 计算方式为向量所有元素的绝对值之和。
n2 = np.linalg.norm(x, ord=2)#2-范数， 计算方式跟欧氏距离的方式一致即向量中各元素的平方和然后求平方根。
n = np.linalg.norm(x, ord=np.inf)#+∞-范数， 所有向量元素绝对值中的最大值
nf = np.linalg.norm(x, ord=-np.inf)#-∞-范数， 所有向量元素绝对值中的最小值
print(n0,n1,n2,n,nf)

2.0 3.0 2.23606797749979 2.0 0.0


# 矩阵的范数

In [7]:
import numpy as np
x = np.array([[-1,1,0],[-4,3,0],[1,0,2]])
print(x)
n1 = np.linalg.norm(x,ord=1) # 一范数，又名列和范数
print(n1)

[[-1  1  0]
 [-4  3  0]
 [ 1  0  2]]
6.0


In [9]:
xtx = np.matmul(x.T,x)
tz = np.linalg.eigvals(xtx)
print(tz)
n2 = np.linalg.norm(x,ord = 2)
print(n2,np.sqrt(tz[0])) #2-范数，又名协范数，计算方法为ATA矩阵的最大特征值的开平方
ninf = np.linalg.norm(x,ord=np.inf)#∞-范数，又名行和范数，即矩阵向量中绝对值之和的最大值。
nfro = np.linalg.norm(x,ord='fro')#F-范数，Frobenius范数，计算方式为矩阵元素的绝对值的平方和再平方
print(ninf,nfro)

[27.71086452  0.03392256  4.25521292]
5.264110990106893 5.264110990106892
7.0 5.656854249492381


In [13]:
A = np.mat('1 2 3;2 3 -5; 4 7 1')
print(A)

[[ 1  2  3]
 [ 2  3 -5]
 [ 4  7  1]]


In [1]:
np.linalg.matrix_rank(A)

NameError: name 'np' is not defined

In [15]:
B = np.mat('3 2 0 5 0;3 -2 3 6 -1;2 0 1 5 -3;1 6 -4 -1 4')
np.linalg.matrix_rank(B)

3