In [13]:
import numpy.matlib
import numpy as np

numpy.matlib.empty((3,4))  # 创建随机矩阵

matrix([[2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.]])

In [14]:
# numpy.matlib.eye() 函数返回一个矩阵，对角线元素为1，其他位置为0
# numpy.matlib.zeros() 0矩阵
# numpy.matlib.ones() 1矩阵
# numpy.matlib.eye(n,M,k,dtype)
# n 
print(numpy.matlib.zeros((2,2)))
print(numpy.matlib.ones((3,3)))
# print(numpy.matlib.eye((3,5)))
print(numpy.matlib.eye(n=3,M=4,k=0,dtype=float))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [24]:
# 对角矩阵 np.matlib.diag()
np.matlib.diag([1,2,4,5,6,7])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 7]])

In [25]:
# numpy.matlib.rand()函数创建一个给定大小的矩阵,数据时随机填充的
# np.matrix() 函数创建矩阵
i = np.matrix([[1,3],[2,4]])
print(i)

[[1 3]
 [2 4]]


In [26]:
np.asarray(i)

array([[1, 3],
       [2, 4]])

In [27]:
np.asmatrix(i)

matrix([[1, 3],
        [2, 4]])

# 矩阵加法

In [19]:
import numpy.matlib
import numpy as np

i = numpy.matlib.empty((3,4))
j = numpy.matlib.empty((3,4))
type(i)  # 类型
i.shape   # 矩阵的结构
print(i)
# i.reshape((4,3))
z = i+j
z

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


matrix([[2., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 2., 0.]])

In [20]:
c = np.matrix([[1,2],[3,4]])
print(c)
d = [1,1]
z = c+d
z

[[1 2]
 [3 4]]


matrix([[2, 3],
        [4, 5]])

# 矩阵间乘法

In [21]:
numpy.matmul(c,d)

matrix([[3, 7]])

# Hadamard 乘积

In [22]:
import numpy.matlib
import numpy as np

a1 = np.matrix([[1,2],[3,4]])
a2 = np.matrix([[1,2],[3,4]])
a1 * a2
numpy.multiply(a1,a2)

matrix([[ 1,  4],
        [ 9, 16]])

# 转置

In [23]:
print(a1)
a1.transpose()

[[1 2]
 [3 4]]


matrix([[1, 3],
        [2, 4]])